In [1]:
import numpy as np
import time

In [2]:
def stringfy(vec):
    return ''.join([str(x) for x in vec])
import itertools
perm = list(itertools.permutations([0,1,2,3]))
ORDER = []
for x in perm:
    el= ''.join([str(y) for y in x])
    ORDER.append(el)

ORDER = np.array(ORDER)

In [3]:
ORDER

array(['0123', '0132', '0213', '0231', '0312', '0321', '1023', '1032',
       '1203', '1230', '1302', '1320', '2013', '2031', '2103', '2130',
       '2301', '2310', '3012', '3021', '3102', '3120', '3201', '3210'],
      dtype='<U4')

In [4]:
CONVERSION = {
    1:1,
    2:2,
    3:3,
    4:4,
    5:5,
    6:6,
    7:7,
    8:0.5,
    9:0.5,
    10:0.5,
}

In [5]:
ACTIONS = {
    'UP' : 0,
    'RIGHT' : 1,
    'DOWN' : 2,
    'LEFT' : 3,
}
class Puzzle4():
    def __init__(self):
        self.config = np.array([0,1,2,3])
        np.random.shuffle(self.config)
        self.final_state = [0,1,2,3]
        self.done = False
        self.num_iter = 0

    def reset(self):
        np.random.shuffle(self.config)
        self.final_state = [0,1,2,3]
        self.done = False
        return stringfy(self.config)

        

    def get_legal_action(self):
        idx_0 = np.argwhere(self.config == 0)[0][0]
        if idx_0 == 0:
            return [ACTIONS['RIGHT'],ACTIONS['DOWN']]
        elif idx_0 == 1:
            return [ACTIONS['LEFT'],ACTIONS['DOWN']]
        elif idx_0 == 2:
            return [ACTIONS['RIGHT'],ACTIONS['UP']]
        else:
            return [ACTIONS['LEFT'],ACTIONS['UP']]

    def action_space(self):
        return 4
        
        
    def step(self,action):
        self.num_iter += 1

        if self.num_iter > 100:
            self.done = True
            return stringfy(self.config), 0, self.done
        if self.done:
            raise Exception('Game is over')
        idx_0 = np.argwhere(self.config == 0)[0][0]
        if action == 0:
            dst = idx_0 - 2 
        elif action == 1:
            dst = idx_0 + 1
        elif action == 2:
            dst = idx_0 + 2
        elif action == 3:
            dst = idx_0 - 1
        else: 
            raise Exception('Invalid action')
    
        self.config[idx_0] = self.config[dst]
        self.config[dst] = 0

        #self.render()


        if np.array_equal(self.config,self.final_state):
            self.done = True
            return stringfy(self.config), 1, self.done
        else:
            return stringfy(self.config), 0, self.done

    
        
    def render(self):
        print(self.config)
    

In [6]:
class QTable():
    def __init__(self,env,eps,alpha,gamma):
        self.env = env
        self.q_table = np.zeros((np.math.factorial(4),env.action_space()))
        self.eps = eps
        self.alpha = alpha
        self.gamma = gamma
    def train(self,num_episodes):
        for _ in range(num_episodes):
            state = self.env.reset()
            idx_state = np.argwhere(ORDER == state)[0][0]
            done = False
            while not done:
                if np.random.random() < self.eps:
                    action = np.random.choice(self.env.get_legal_action())
                else:
                    action = np.argmax(self.q_table[idx_state])
                
                new_state,reward,done = self.env.step(action)
                idx_new_state = np.argwhere(ORDER == new_state)[0][0]
                
                
                self.q_table[idx_state,action] =self.q_table[idx_state,action] + self.alpha*(reward + self.gamma*np.max(self.q_table[idx_new_state,:]-self.q_table[idx_state,action]))
                state = new_state
                idx_state = idx_new_state

                #time.sleep(0.5)
        

In [7]:
env = Puzzle4()
q_table = QTable(env,0.1,0.1,0.9)

In [8]:
q_table.train(10000)

[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[0 2 1 3]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 0 1 3]
[2 3 1 0]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]
[0 3 2 1]
[2 3 0 1]


In [82]:
env.config

array([1, 2, 3, 0])

In [84]:
env.step(3)

[0 1 3 2]


('0132', 0, False)